package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}

	public java.lang.Long getLogId() {
		return get("log_id");
	}

	public void setLogAdminName(java.lang.String logAdminName) {
		set("log_admin_name", logAdminName);
	}

	public java.lang.String getLogAdminName() {
		return get("log_admin_name");
	}

	public void setLogObj(java.lang.String logObj) {
		set("log_obj", logObj);
	}

	public java.lang.String getLogObj() {
		return get("log_obj");
	}

	public void setLogOper(java.lang.String logOper) {
		set("log_oper", logOper);
	}

	public java.lang.String getLogOper() {
		return get("log_oper");
	}

	public void setLogTime(java.util.Date logTime) {
		set("log_time", logTime);
	}

	public java.util.Date getLogTime() {
		return get("log_time");
	}

	public void setLogContent(java.lang.String logContent) {
		set("log_content", logContent);
	}

	public java.lang.String getLogContent() {
		return get("log_content");
	}

	public void setLogStatus(java.lang.String logStatus) {
		set("log_status", logStatus);
	}

	public java.lang.String getLogStatus() {
		return get("log_status");
	}

}
