package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfWeixin<M extends BaseConfWeixin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setWeixinAppid(java.lang.String weixinAppid) {
		set("weixin_appid", weixinAppid);
	}

	public java.lang.String getWeixinAppid() {
		return get("weixin_appid");
	}

	public void setWeixinSecret(java.lang.String weixinSecret) {
		set("weixin_secret", weixinSecret);
	}

	public java.lang.String getWeixinSecret() {
		return get("weixin_secret");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setEncryptMessage(java.lang.String encryptMessage) {
		set("encrypt_message", encryptMessage);
	}

	public java.lang.String getEncryptMessage() {
		return get("encrypt_message");
	}

	public void setEncodingAeskey(java.lang.String encodingAeskey) {
		set("encoding_aeskey", encodingAeskey);
	}

	public java.lang.String getEncodingAeskey() {
		return get("encoding_aeskey");
	}

	public void setSubscribeUrl(java.lang.String subscribeUrl) {
		set("subscribe_url", subscribeUrl);
	}

	public java.lang.String getSubscribeUrl() {
		return get("subscribe_url");
	}

	public void setMchId(java.lang.String mchId) {
		set("mch_id", mchId);
	}

	public java.lang.String getMchId() {
		return get("mch_id");
	}

	public void setMchKey(java.lang.String mchKey) {
		set("mch_key", mchKey);
	}

	public java.lang.String getMchKey() {
		return get("mch_key");
	}

}
