package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecordPifuSubscribe<M extends BaseRecordPifuSubscribe<M>> extends Model<M> implements IBean {

	public void setSubscribeId(java.lang.Long subscribeId) {
		set("subscribe_id", subscribeId);
	}

	public java.lang.Long getSubscribeId() {
		return get("subscribe_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setSubscribeTime(java.util.Date subscribeTime) {
		set("subscribe_time", subscribeTime);
	}

	public java.util.Date getSubscribeTime() {
		return get("subscribe_time");
	}

	public void setPifuType(java.lang.String pifuType) {
		set("pifu_type", pifuType);
	}

	public java.lang.String getPifuType() {
		return get("pifu_type");
	}

	public void setSequenceCurrent(java.lang.Integer sequenceCurrent) {
		set("sequence_current", sequenceCurrent);
	}

	public java.lang.Integer getSequenceCurrent() {
		return get("sequence_current");
	}

}
