package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataQuestion<M extends BaseDataQuestion<M>> extends Model<M> implements IBean {

	public void setQuestionId(java.lang.Long questionId) {
		set("question_id", questionId);
	}

	public java.lang.Long getQuestionId() {
		return get("question_id");
	}

	public void setPhysiqueNo(java.lang.String physiqueNo) {
		set("physique_no", physiqueNo);
	}

	public java.lang.String getPhysiqueNo() {
		return get("physique_no");
	}

	public void setQuestionContent(java.lang.String questionContent) {
		set("question_content", questionContent);
	}

	public java.lang.String getQuestionContent() {
		return get("question_content");
	}

}
