package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataItem<M extends BaseDataItem<M>> extends Model<M> implements IBean {

	public void setItemId(java.lang.Long itemId) {
		set("item_id", itemId);
	}

	public java.lang.Long getItemId() {
		return get("item_id");
	}

	public void setItemTypeId(java.lang.Long itemTypeId) {
		set("item_type_id", itemTypeId);
	}

	public java.lang.Long getItemTypeId() {
		return get("item_type_id");
	}

	public void setItemName(java.lang.String itemName) {
		set("item_name", itemName);
	}

	public java.lang.String getItemName() {
		return get("item_name");
	}

	public void setItemImage(java.lang.String itemImage) {
		set("item_image", itemImage);
	}

	public java.lang.String getItemImage() {
		return get("item_image");
	}

	public void setItemTitle1(java.lang.String itemTitle1) {
		set("item_title1", itemTitle1);
	}

	public java.lang.String getItemTitle1() {
		return get("item_title1");
	}

	public void setItemContent1(java.lang.String itemContent1) {
		set("item_content1", itemContent1);
	}

	public java.lang.String getItemContent1() {
		return get("item_content1");
	}

	public void setItemTitle2(java.lang.String itemTitle2) {
		set("item_title2", itemTitle2);
	}

	public java.lang.String getItemTitle2() {
		return get("item_title2");
	}

	public void setItemContent2(java.lang.String itemContent2) {
		set("item_content2", itemContent2);
	}

	public java.lang.String getItemContent2() {
		return get("item_content2");
	}

	public void setItemTitle3(java.lang.String itemTitle3) {
		set("item_title3", itemTitle3);
	}

	public java.lang.String getItemTitle3() {
		return get("item_title3");
	}

	public void setItemContent3(java.lang.String itemContent3) {
		set("item_content3", itemContent3);
	}

	public java.lang.String getItemContent3() {
		return get("item_content3");
	}

}
