package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataDemand<M extends BaseDataDemand<M>> extends Model<M> implements IBean {

	public void setDemandId(java.lang.Long demandId) {
		set("demand_id", demandId);
	}

	public java.lang.Long getDemandId() {
		return get("demand_id");
	}

	public void setDemandNo(java.lang.String demandNo) {
		set("demand_no", demandNo);
	}

	public java.lang.String getDemandNo() {
		return get("demand_no");
	}

	public void setDemandName(java.lang.String demandName) {
		set("demand_name", demandName);
	}

	public java.lang.String getDemandName() {
		return get("demand_name");
	}

	public void setDemandSecondName(java.lang.String demandSecondName) {
		set("demand_second_name", demandSecondName);
	}

	public java.lang.String getDemandSecondName() {
		return get("demand_second_name");
	}

}
