package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecordTest<M extends BaseRecordTest<M>> extends Model<M> implements IBean {

	public void setTestId(java.lang.Long testId) {
		set("test_id", testId);
	}

	public java.lang.Long getTestId() {
		return get("test_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setSolutionNo(java.lang.String solutionNo) {
		set("solution_no", solutionNo);
	}

	public java.lang.String getSolutionNo() {
		return get("solution_no");
	}

	public void setDemandNo(java.lang.String demandNo) {
		set("demand_no", demandNo);
	}

	public java.lang.String getDemandNo() {
		return get("demand_no");
	}

	public void setTestFeature(java.lang.String testFeature) {
		set("test_feature", testFeature);
	}

	public java.lang.String getTestFeature() {
		return get("test_feature");
	}

	public void setTestTongue(java.lang.String testTongue) {
		set("test_tongue", testTongue);
	}

	public java.lang.String getTestTongue() {
		return get("test_tongue");
	}

	public void setTestTongueResult(java.lang.String testTongueResult) {
		set("test_tongue_result", testTongueResult);
	}

	public java.lang.String getTestTongueResult() {
		return get("test_tongue_result");
	}

	public void setTestScore(java.lang.Integer testScore) {
		set("test_score", testScore);
	}

	public java.lang.Integer getTestScore() {
		return get("test_score");
	}

	public void setTestScoreList(java.lang.String testScoreList) {
		set("test_score_list", testScoreList);
	}

	public java.lang.String getTestScoreList() {
		return get("test_score_list");
	}

	public void setTestTime(java.util.Date testTime) {
		set("test_time", testTime);
	}

	public java.util.Date getTestTime() {
		return get("test_time");
	}

}
