package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataSolution<M extends BaseDataSolution<M>> extends Model<M> implements IBean {

	public void setSolutionId(java.lang.Long solutionId) {
		set("solution_id", solutionId);
	}

	public java.lang.Long getSolutionId() {
		return get("solution_id");
	}

	public void setPhysiqueNo(java.lang.String physiqueNo) {
		set("physique_no", physiqueNo);
	}

	public java.lang.String getPhysiqueNo() {
		return get("physique_no");
	}

	public void setSolutionNo(java.lang.String solutionNo) {
		set("solution_no", solutionNo);
	}

	public java.lang.String getSolutionNo() {
		return get("solution_no");
	}

	public void setChayin1(java.lang.String chayin1) {
		set("chayin1", chayin1);
	}

	public java.lang.String getChayin1() {
		return get("chayin1");
	}

	public void setChayin2(java.lang.String chayin2) {
		set("chayin2", chayin2);
	}

	public java.lang.String getChayin2() {
		return get("chayin2");
	}

	public void setChayin3(java.lang.String chayin3) {
		set("chayin3", chayin3);
	}

	public java.lang.String getChayin3() {
		return get("chayin3");
	}

	public void setBaguan1(java.lang.String baguan1) {
		set("baguan1", baguan1);
	}

	public java.lang.String getBaguan1() {
		return get("baguan1");
	}

	public void setBaguan2(java.lang.String baguan2) {
		set("baguan2", baguan2);
	}

	public java.lang.String getBaguan2() {
		return get("baguan2");
	}

	public void setBaguan3(java.lang.String baguan3) {
		set("baguan3", baguan3);
	}

	public java.lang.String getBaguan3() {
		return get("baguan3");
	}

	public void setZuyu1(java.lang.String zuyu1) {
		set("zuyu1", zuyu1);
	}

	public java.lang.String getZuyu1() {
		return get("zuyu1");
	}

	public void setZuyu2(java.lang.String zuyu2) {
		set("zuyu2", zuyu2);
	}

	public java.lang.String getZuyu2() {
		return get("zuyu2");
	}

	public void setZuyu3(java.lang.String zuyu3) {
		set("zuyu3", zuyu3);
	}

	public java.lang.String getZuyu3() {
		return get("zuyu3");
	}

	public void setAijiu1(java.lang.String aijiu1) {
		set("aijiu1", aijiu1);
	}

	public java.lang.String getAijiu1() {
		return get("aijiu1");
	}

	public void setAijiu2(java.lang.String aijiu2) {
		set("aijiu2", aijiu2);
	}

	public java.lang.String getAijiu2() {
		return get("aijiu2");
	}

	public void setAijiu3(java.lang.String aijiu3) {
		set("aijiu3", aijiu3);
	}

	public java.lang.String getAijiu3() {
		return get("aijiu3");
	}

	public void setTiefu1(java.lang.String tiefu1) {
		set("tiefu1", tiefu1);
	}

	public java.lang.String getTiefu1() {
		return get("tiefu1");
	}

	public void setTiefu2(java.lang.String tiefu2) {
		set("tiefu2", tiefu2);
	}

	public java.lang.String getTiefu2() {
		return get("tiefu2");
	}

	public void setTiefu3(java.lang.String tiefu3) {
		set("tiefu3", tiefu3);
	}

	public java.lang.String getTiefu3() {
		return get("tiefu3");
	}

}
