package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecordPifuTest<M extends BaseRecordPifuTest<M>> extends Model<M> implements IBean {

	public void setTestId(java.lang.Long testId) {
		set("test_id", testId);
	}

	public java.lang.Long getTestId() {
		return get("test_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setTestTime(java.util.Date testTime) {
		set("test_time", testTime);
	}

	public java.util.Date getTestTime() {
		return get("test_time");
	}

	public void setPifuType(java.lang.String pifuType) {
		set("pifu_type", pifuType);
	}

	public java.lang.String getPifuType() {
		return get("pifu_type");
	}

}
