package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataSubscribe<M extends BaseDataSubscribe<M>> extends Model<M> implements IBean {

	public void setSubscribeId(java.lang.Long subscribeId) {
		set("subscribe_id", subscribeId);
	}

	public java.lang.Long getSubscribeId() {
		return get("subscribe_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setSubscribeType(java.lang.String subscribeType) {
		set("subscribe_type", subscribeType);
	}

	public java.lang.String getSubscribeType() {
		return get("subscribe_type");
	}

	public void setSubscribeItem(java.lang.String subscribeItem) {
		set("subscribe_item", subscribeItem);
	}

	public java.lang.String getSubscribeItem() {
		return get("subscribe_item");
	}

	public void setSubscribeSol(java.lang.String subscribeSol) {
		set("subscribe_sol", subscribeSol);
	}

	public java.lang.String getSubscribeSol() {
		return get("subscribe_sol");
	}

	public void setSubscribePost(java.lang.Long subscribePost) {
		set("subscribe_post", subscribePost);
	}

	public java.lang.Long getSubscribePost() {
		return get("subscribe_post");
	}

}
