package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataPifuSol<M extends BaseDataPifuSol<M>> extends Model<M> implements IBean {

	public void setSolId(java.lang.Long solId) {
		set("sol_id", solId);
	}

	public java.lang.Long getSolId() {
		return get("sol_id");
	}

	public void setPifuType(java.lang.String pifuType) {
		set("pifu_type", pifuType);
	}

	public java.lang.String getPifuType() {
		return get("pifu_type");
	}

	public void setSolSequence(java.lang.Integer solSequence) {
		set("sol_sequence", solSequence);
	}

	public java.lang.Integer getSolSequence() {
		return get("sol_sequence");
	}

	public void setSolContent(java.lang.String solContent) {
		set("sol_content", solContent);
	}

	public java.lang.String getSolContent() {
		return get("sol_content");
	}

}
