package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysAdmin<M extends BaseSysAdmin<M>> extends Model<M> implements IBean {

	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}

	public java.lang.Long getAdminId() {
		return get("admin_id");
	}

	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}

	public java.lang.String getAdminName() {
		return get("admin_name");
	}

	public void setAdminPwd(java.lang.String adminPwd) {
		set("admin_pwd", adminPwd);
	}

	public java.lang.String getAdminPwd() {
		return get("admin_pwd");
	}

	public void setAdminRank(java.lang.String adminRank) {
		set("admin_rank", adminRank);
	}

	public java.lang.String getAdminRank() {
		return get("admin_rank");
	}

}
