package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfOauth<M extends BaseConfOauth<M>> extends Model<M> implements IBean {

	public void setOauthId(java.lang.Long oauthId) {
		set("oauth_id", oauthId);
	}

	public java.lang.Long getOauthId() {
		return get("oauth_id");
	}

	public void setOauthTitle(java.lang.String oauthTitle) {
		set("oauth_title", oauthTitle);
	}

	public java.lang.String getOauthTitle() {
		return get("oauth_title");
	}

	public void setOauthLink(java.lang.String oauthLink) {
		set("oauth_link", oauthLink);
	}

	public java.lang.String getOauthLink() {
		return get("oauth_link");
	}

	public void setOauthShortLink(java.lang.String oauthShortLink) {
		set("oauth_short_link", oauthShortLink);
	}

	public java.lang.String getOauthShortLink() {
		return get("oauth_short_link");
	}

}
