package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataChanpin<M extends BaseDataChanpin<M>> extends Model<M> implements IBean {

	public void setChanpinId(java.lang.Long chanpinId) {
		set("chanpin_id", chanpinId);
	}

	public java.lang.Long getChanpinId() {
		return get("chanpin_id");
	}

	public void setPhysiqueNo(java.lang.String physiqueNo) {
		set("physique_no", physiqueNo);
	}

	public java.lang.String getPhysiqueNo() {
		return get("physique_no");
	}

	public void setChanpinName(java.lang.String chanpinName) {
		set("chanpin_name", chanpinName);
	}

	public java.lang.String getChanpinName() {
		return get("chanpin_name");
	}

	public void setChanpinLink(java.lang.String chanpinLink) {
		set("chanpin_link", chanpinLink);
	}

	public java.lang.String getChanpinLink() {
		return get("chanpin_link");
	}

	public void setChanpinColor(java.lang.String chanpinColor) {
		set("chanpin_color", chanpinColor);
	}

	public java.lang.String getChanpinColor() {
		return get("chanpin_color");
	}

	public void setChanpinImage(java.lang.String chanpinImage) {
		set("chanpin_image", chanpinImage);
	}

	public java.lang.String getChanpinImage() {
		return get("chanpin_image");
	}

}
