package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfTime<M extends BaseConfTime<M>> extends Model<M> implements IBean {

	public void setTimeId(java.lang.Long timeId) {
		set("time_id", timeId);
	}

	public java.lang.Long getTimeId() {
		return get("time_id");
	}

	public void setTimePifuTest(java.lang.Integer timePifuTest) {
		set("time_pifu_test", timePifuTest);
	}

	public java.lang.Integer getTimePifuTest() {
		return get("time_pifu_test");
	}

	public void setTimePifuPostSol(java.lang.Integer timePifuPostSol) {
		set("time_pifu_post_sol", timePifuPostSol);
	}

	public java.lang.Integer getTimePifuPostSol() {
		return get("time_pifu_post_sol");
	}

}
