package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataSolution<M extends BaseDataSolution<M>> extends Model<M> implements IBean {

	public void setSolutionId(java.lang.Long solutionId) {
		set("solution_id", solutionId);
	}

	public java.lang.Long getSolutionId() {
		return get("solution_id");
	}

	public void setSolutionNo(java.lang.String solutionNo) {
		set("solution_no", solutionNo);
	}

	public java.lang.String getSolutionNo() {
		return get("solution_no");
	}

	public void setPhysiqueNo(java.lang.String physiqueNo) {
		set("physique_no", physiqueNo);
	}

	public java.lang.String getPhysiqueNo() {
		return get("physique_no");
	}

	public void setSolutionScoreUp(java.lang.Integer solutionScoreUp) {
		set("solution_score_up", solutionScoreUp);
	}

	public java.lang.Integer getSolutionScoreUp() {
		return get("solution_score_up");
	}

	public void setSolutionScoreDown(java.lang.Integer solutionScoreDown) {
		set("solution_score_down", solutionScoreDown);
	}

	public java.lang.Integer getSolutionScoreDown() {
		return get("solution_score_down");
	}

	public void setSolutionChayin(java.lang.String solutionChayin) {
		set("solution_chayin", solutionChayin);
	}

	public java.lang.String getSolutionChayin() {
		return get("solution_chayin");
	}

	public void setSolutionZuyu(java.lang.String solutionZuyu) {
		set("solution_zuyu", solutionZuyu);
	}

	public java.lang.String getSolutionZuyu() {
		return get("solution_zuyu");
	}

	public void setSolutionBaguan(java.lang.String solutionBaguan) {
		set("solution_baguan", solutionBaguan);
	}

	public java.lang.String getSolutionBaguan() {
		return get("solution_baguan");
	}

	public void setSolutionAijiu(java.lang.String solutionAijiu) {
		set("solution_aijiu", solutionAijiu);
	}

	public java.lang.String getSolutionAijiu() {
		return get("solution_aijiu");
	}

	public void setSolutionTiefu(java.lang.String solutionTiefu) {
		set("solution_tiefu", solutionTiefu);
	}

	public java.lang.String getSolutionTiefu() {
		return get("solution_tiefu");
	}

	public void setSolutionMianmo(java.lang.String solutionMianmo) {
		set("solution_mianmo", solutionMianmo);
	}

	public java.lang.String getSolutionMianmo() {
		return get("solution_mianmo");
	}

	public void setSolutionYishi(java.lang.String solutionYishi) {
		set("solution_yishi", solutionYishi);
	}

	public java.lang.String getSolutionYishi() {
		return get("solution_yishi");
	}

	public void setSolutionJishi(java.lang.String solutionJishi) {
		set("solution_jishi", solutionJishi);
	}

	public java.lang.String getSolutionJishi() {
		return get("solution_jishi");
	}

}
