package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataItemType<M extends BaseDataItemType<M>> extends Model<M> implements IBean {

	public void setItemTypeId(java.lang.Long itemTypeId) {
		set("item_type_id", itemTypeId);
	}

	public java.lang.Long getItemTypeId() {
		return get("item_type_id");
	}

	public void setItemTypeName(java.lang.String itemTypeName) {
		set("item_type_name", itemTypeName);
	}

	public java.lang.String getItemTypeName() {
		return get("item_type_name");
	}

}
