package com.jhs.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataImage<M extends BaseDataImage<M>> extends Model<M> implements IBean {

	public void setImageId(java.lang.Long imageId) {
		set("image_id", imageId);
	}

	public java.lang.Long getImageId() {
		return get("image_id");
	}

	public void setImageTypeId(java.lang.Long imageTypeId) {
		set("image_type_id", imageTypeId);
	}

	public java.lang.Long getImageTypeId() {
		return get("image_type_id");
	}

	public void setImageName(java.lang.String imageName) {
		set("image_name", imageName);
	}

	public java.lang.String getImageName() {
		return get("image_name");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

	public void setImagePath(java.lang.String imagePath) {
		set("image_path", imagePath);
	}

	public java.lang.String getImagePath() {
		return get("image_path");
	}

	public void setImageCreateTime(java.util.Date imageCreateTime) {
		set("image_create_time", imageCreateTime);
	}

	public java.util.Date getImageCreateTime() {
		return get("image_create_time");
	}

}
