package com.jhs.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("conf_oauth", "oauth_id", ConfOauth.class);
		arp.addMapping("conf_time", "time_id", ConfTime.class);
		arp.addMapping("conf_weixin", "id", ConfWeixin.class);
		arp.addMapping("data_chanpin", "chanpin_id", DataChanpin.class);
		arp.addMapping("data_demand", "demand_id", DataDemand.class);
		arp.addMapping("data_image", "image_id", DataImage.class);
		arp.addMapping("data_image_type", "type_id", DataImageType.class);
		arp.addMapping("data_item", "item_id", DataItem.class);
		arp.addMapping("data_item_type", "item_type_id", DataItemType.class);
		arp.addMapping("data_physique", "physique_id", DataPhysique.class);
		arp.addMapping("data_pifu_sol", "sol_id", DataPifuSol.class);
		arp.addMapping("data_question", "question_id", DataQuestion.class);
		arp.addMapping("data_solution", "solution_id", DataSolution.class);
		arp.addMapping("data_subscribe", "subscribe_id", DataSubscribe.class);
		arp.addMapping("data_tiaoli", "tiaoli_id", DataTiaoli.class);
		arp.addMapping("data_xuewei", "xuewei_id", DataXuewei.class);
		arp.addMapping("record_pifu_subscribe", "subscribe_id", RecordPifuSubscribe.class);
		arp.addMapping("record_pifu_test", "test_id", RecordPifuTest.class);
		arp.addMapping("record_test", "test_id", RecordTest.class);
		arp.addMapping("record_user", "user_id", RecordUser.class);
		arp.addMapping("sys_admin", "admin_id", SysAdmin.class);
		arp.addMapping("sys_log", "log_id", SysLog.class);
	}
}

