package com.jhs.common.model;

import com.jhs.common.model.base.BaseConfOauth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfOauth extends BaseConfOauth<ConfOauth> {
	public static final ConfOauth dao = new ConfOauth().dao();
}
