package com.jhs.common.model;

import com.jhs.common.model.base.BaseConfTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfTime extends BaseConfTime<ConfTime> {
	public static final ConfTime dao = new ConfTime().dao();
}
