package com.jhs.common.model;

import com.jhs.common.model.base.BaseConfWeixin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfWeixin extends BaseConfWeixin<ConfWeixin> {
	
}
