package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataQuestion extends BaseDataQuestion<DataQuestion> {
	
}
