package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataChanpin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataChanpin extends BaseDataChanpin<DataChanpin> {
	public static final DataChanpin dao = new DataChanpin().dao();
}
