package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataItemType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataItemType extends BaseDataItemType<DataItemType> {
	public static final DataItemType dao = new DataItemType().dao();
}
