package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataPhysique;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataPhysique extends BaseDataPhysique<DataPhysique> {
	public static final DataPhysique dao = new DataPhysique().dao();
}
