package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataXuewei;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataXuewei extends BaseDataXuewei<DataXuewei> {
	public static final DataXuewei dao = new DataXuewei().dao();
}
