package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataPifuSol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataPifuSol extends BaseDataPifuSol<DataPifuSol> {
	public static final DataPifuSol dao = new DataPifuSol().dao();
}
