package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataDemand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDemand extends BaseDataDemand<DataDemand> {
	
}
