package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataSubscribe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataSubscribe extends BaseDataSubscribe<DataSubscribe> {
	public static final DataSubscribe dao = new DataSubscribe().dao();
}
