package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataSolution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataSolution extends BaseDataSolution<DataSolution> {
	
}
