package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataItem extends BaseDataItem<DataItem> {
	public static final DataItem dao = new DataItem().dao();
}
