package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataTiaoli;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataTiaoli extends BaseDataTiaoli<DataTiaoli> {
	public static final DataTiaoli dao = new DataTiaoli().dao();
}
