package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataImageType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataImageType extends BaseDataImageType<DataImageType> {
	public static final DataImageType dao = new DataImageType().dao();
}
