package com.jhs.common.model;

import com.jhs.common.model.base.BaseDataImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataImage extends BaseDataImage<DataImage> {
	public static final DataImage dao = new DataImage().dao();
}
