package com.jhs.common.model;

import com.jhs.common.model.base.BaseRecordPifuSubscribe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordPifuSubscribe extends BaseRecordPifuSubscribe<RecordPifuSubscribe> {
	public static final RecordPifuSubscribe dao = new RecordPifuSubscribe().dao();
}
