package com.jhs.common.model;

import com.jhs.common.model.base.BaseRecordTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordTest extends BaseRecordTest<RecordTest> {
	
}
