package com.jhs.common.model;

import com.jhs.common.model.base.BaseRecordUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordUser extends BaseRecordUser<RecordUser> {
	public static final RecordUser dao = new RecordUser().dao();
}
