package com.jhs.common.model;

import com.jhs.common.model.base.BaseRecordPifuTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordPifuTest extends BaseRecordPifuTest<RecordPifuTest> {
	public static final RecordPifuTest dao = new RecordPifuTest().dao();
}
