package com.jhs.common.model;

import com.jhs.common.model.base.BaseSysLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
	public static final SysLog dao = new SysLog().dao();
}
